# SPDX-FileContributor: Arthit Suriyawongkul
# SPDX-FileCopyrightText: 2026-present Arthit Suriyawongkul
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0

"""Tests for SPDX 3.0 SHACL shape constraints (structural equivalent):
Agent/Tool typing on CreationInfo, @graph element ordering and
determinism, blank-node/named-element deduplication, and provenance
Annotation compliance.

See also: test_spdx3_compliance_structure.py -- this module's sibling,
split from the original test_spdx3_compliance.py.
"""

import dataclasses
import json
import re
import tempfile
from pathlib import Path
from typing import Any

from pitloom.assemble import generate_project_sbom
from pitloom.core.creation import CreationMetadata
from pitloom.export.spdx3_json import (
    _deduplicate_creation_infos,
    _deduplicate_named_elements,
    _graph_sort_key,
)
from pitloom.extract.project import read_project

# SPDX 3.0 SHACL: sh:class spdx:Agent; sh:path spdx:createdBy
# Agent subclasses per the SPDX 3.0 OWL ontology
_AGENT_TYPES: frozenset[str] = frozenset(
    {"Person", "Organization", "SoftwareAgent", "Agent"}
)


def _build_spdx_id_type_map(graph: list[dict[str, Any]]) -> dict[str, str]:
    """Return a mapping of spdxId -> JSON-LD type for all elements."""
    return {elem["spdxId"]: elem["type"] for elem in graph if "spdxId" in elem}


def test_spdx3_shacl_creation_info_created_by_are_agents() -> None:
    """createdBy must reference only Agent elements.

    Replicates the SPDX 3.0 SHACL shape::

        [] sh:class spdx:Agent ;
           sh:minCount 1 ;
           sh:path spdx:createdBy .

    Agent subclasses are Person, Organization, and SoftwareAgent (the default
    creator for an unattended run).  Tool is NOT an Agent subclass; placing a
    Tool in createdBy causes a SHACL violation -- Tools go in createdUsing.
    """
    pyproject_content = """
[project]
name = "shacl-agent-test"
version = "1.0.0"
"""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        (tmppath / "pyproject.toml").write_text(pyproject_content)

        sbom_json = generate_project_sbom(tmppath)
        graph: list[dict[str, Any]] = json.loads(sbom_json)["@graph"]

        id_to_type = _build_spdx_id_type_map(graph)
        creation_infos = [e for e in graph if e["type"] == "CreationInfo"]

        assert creation_infos, "SBOM must contain at least one CreationInfo"

        for ci in creation_infos:
            created_by = ci.get("createdBy", [])
            assert created_by, "CreationInfo.createdBy must have at least one entry"

            for ref_id in created_by:
                elem_type = id_to_type.get(ref_id)
                assert elem_type in _AGENT_TYPES, (
                    f"createdBy references '{ref_id}' of type {elem_type!r}. "
                    "Only Agent subclasses (Person, Organization, "
                    "SoftwareAgent) are allowed. Tool must go in createdUsing."
                )


def test_spdx3_shacl_creation_info_created_using_are_tools() -> None:
    """createdUsing must reference only Tool elements.

    Replicates the SPDX 3.0.1 SHACL shape for the optional createdUsing path::

        [] sh:class spdx:Tool ;
           sh:path spdx:createdUsing .
    """
    pyproject_content = """
[project]
name = "shacl-tool-test"
version = "1.0.0"
"""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        (tmppath / "pyproject.toml").write_text(pyproject_content)

        sbom_json = generate_project_sbom(tmppath)
        graph: list[dict[str, Any]] = json.loads(sbom_json)["@graph"]

        id_to_type = _build_spdx_id_type_map(graph)
        creation_infos = [e for e in graph if e["type"] == "CreationInfo"]

        for ci in creation_infos:
            for ref_id in ci.get("createdUsing", []):
                elem_type = id_to_type.get(ref_id)
                assert elem_type == "Tool", (
                    f"createdUsing references '{ref_id}' of type {elem_type!r}. "
                    "Only Tool elements are allowed in createdUsing."
                )


def test_spdx3_shacl_creation_info_has_tool() -> None:
    """Generated SBOM must include a Tool element declared via createdUsing.

    This is not a SPDX 3.0 requirement but every SBOM generated by Pitloom
    should include a Tool element.
    """
    pyproject_content = """
[project]
name = "shacl-has-tool-test"
version = "1.0.0"
"""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        (tmppath / "pyproject.toml").write_text(pyproject_content)

        sbom_json = generate_project_sbom(tmppath)
        graph: list[dict[str, Any]] = json.loads(sbom_json)["@graph"]

        element_types = {e["type"] for e in graph}
        assert "Tool" in element_types, (
            "SBOM must contain a Tool element representing the generation tool"
        )

        creation_infos = [e for e in graph if e["type"] == "CreationInfo"]
        for ci in creation_infos:
            assert ci.get("createdUsing"), (
                "CreationInfo must reference the generation tool via createdUsing"
            )


def test_graph_element_ordering() -> None:
    """@graph elements must follow the canonical priority order.

    Required order:
      0. CreationInfo   -- blank node referenced by every element
      1. SpdxDocument   -- document envelope / profileConformance
      2. software_Sbom  -- root element pointer / sbomType
      3+ everything else, sorted by spdxId/@id

    This test also verifies that repeated calls produce identical output
    (i.e., ordering is deterministic across runs).
    """
    pyproject_content = """
[project]
name = "ordering-test"
version = "1.0.0"
dependencies = ["requests>=2.28.0"]
"""
    # Fixed timestamp so two calls with identical inputs produce identical output.
    # Without this, datetime.now() is called on each invocation and the
    # CreationInfo.created field would differ between runs.
    fixed_ci = CreationMetadata(creation_datetime="2026-01-01T00:00:00+00:00")

    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        (tmppath / "pyproject.toml").write_text(pyproject_content)

        sbom_json_1 = generate_project_sbom(tmppath, creation_metadata=fixed_ci)
        sbom_json_2 = generate_project_sbom(tmppath, creation_metadata=fixed_ci)

        # Determinism: two calls with identical inputs must produce identical output
        assert sbom_json_1 == sbom_json_2, (
            "@graph order is not deterministic across runs"
        )

        graph: list[dict[str, Any]] = json.loads(sbom_json_1)["@graph"]
        types = [e["type"] for e in graph]

        # Priority elements must appear before everything else
        assert "CreationInfo" in types
        assert "SpdxDocument" in types
        assert "software_Sbom" in types

        ci_idx = types.index("CreationInfo")
        doc_idx = types.index("SpdxDocument")
        sbom_idx = types.index("software_Sbom")

        assert ci_idx < doc_idx, "CreationInfo must precede SpdxDocument"
        assert doc_idx < sbom_idx, "SpdxDocument must precede software_Sbom"

        # If a core Bom element is present it must sit between SpdxDocument
        # and software_Sbom (priority 2, between 1 and 3).
        if "Bom" in types:
            bom_idx = types.index("Bom")
            assert doc_idx < bom_idx < sbom_idx, (
                "Bom must appear after SpdxDocument and before software_Sbom"
            )

        # All priority elements must appear before the general population
        priority_types = {"CreationInfo", "SpdxDocument", "Bom", "software_Sbom"}
        first_other = next(
            (i for i, e in enumerate(graph) if e["type"] not in priority_types),
            len(graph),
        )
        assert sbom_idx < first_other, (
            "All priority elements must precede non-priority elements"
        )


def test_creation_info_deduplication() -> None:
    """Identical CreationInfo blank nodes must be collapsed to one canonical node."""
    ci_shared = {
        "type": "CreationInfo",
        "@id": "_:CreationInfo0",
        "specVersion": "3.0.1",
        "created": "2026-01-01T00:00:00Z",
        "createdBy": ["https://example.org/Person-1"],
        "createdUsing": ["https://example.org/Tool-1"],
    }
    ci_duplicate = {**ci_shared, "@id": "_:CreationInfo1"}
    pkg = {
        "type": "software_Package",
        "spdxId": "https://example.org/Package-1",
        "creationInfo": "_:CreationInfo1",
        "name": "example",
    }
    graph: list[dict[str, Any]] = [ci_shared, ci_duplicate, pkg]

    result = _deduplicate_creation_infos(graph)

    ci_nodes = [e for e in result if e["type"] == "CreationInfo"]
    assert len(ci_nodes) == 1, "Duplicate CreationInfo must be removed"
    canonical_id = ci_nodes[0]["@id"]

    pkg_result = next(e for e in result if e["type"] == "software_Package")
    assert pkg_result["creationInfo"] == canonical_id, (
        "Reference to removed CreationInfo must be redirected to canonical node"
    )


def test_creation_info_deduplication_distinct_kept() -> None:
    """CreationInfo nodes with different content must both be retained."""
    ci_a = {
        "type": "CreationInfo",
        "@id": "_:CreationInfo0",
        "specVersion": "3.0.1",
        "created": "2026-01-01T00:00:00Z",
        "createdBy": ["https://example.org/Person-1"],
        "createdUsing": [],
    }
    ci_b = {
        "type": "CreationInfo",
        "@id": "_:CreationInfo1",
        "specVersion": "3.0.1",
        "created": "2026-06-01T00:00:00Z",  # different timestamp
        "createdBy": ["https://example.org/Person-1"],
        "createdUsing": [],
    }
    graph = [ci_a, ci_b]

    result = _deduplicate_creation_infos(graph)
    assert len(result) == 2, "Distinct CreationInfo nodes must not be merged"


def test_named_element_deduplication_identical() -> None:
    """Exact-duplicate named elements (same spdxId, same content) collapse to one."""
    pkg = {
        "type": "software_Package",
        "spdxId": "https://example.org/Package-1",
        "name": "example",
        "creationInfo": "_:CreationInfo0",
    }
    graph: list[dict[str, Any]] = [dict(pkg), dict(pkg)]

    result = _deduplicate_named_elements(graph)
    assert len(result) == 1, "Identical named elements must be deduplicated"
    assert result[0]["spdxId"] == pkg["spdxId"]


def test_named_element_deduplication_conflict_retained() -> None:
    """Named elements with the same spdxId but different content must all be kept."""
    pkg_a = {
        "type": "software_Package",
        "spdxId": "https://example.org/Package-1",
        "name": "example",
        "software_packageVersion": "1.0.0",
    }
    pkg_b = {**pkg_a, "software_packageVersion": "1.0.1"}  # version differs
    graph: list[dict[str, Any]] = [pkg_a, pkg_b]

    result = _deduplicate_named_elements(graph)
    assert len(result) == 2, "Conflicting named elements must all be retained"


def test_named_element_deduplication_no_spdx_id_passthrough() -> None:
    """Elements without spdxId (blank nodes) must pass through untouched."""
    ci = {
        "type": "CreationInfo",
        "@id": "_:CreationInfo0",
        "specVersion": "3.0.1",
        "created": "2026-01-01T00:00:00Z",
    }
    graph: list[dict[str, Any]] = [ci]

    result = _deduplicate_named_elements(graph)
    assert result == graph


def test_graph_sort_key_priority_order() -> None:
    """_graph_sort_key must assign lower values to higher-priority types."""
    elements = [
        {"type": "software_Sbom", "spdxId": "https://example.org/Sbom-1"},
        {"type": "Bom", "spdxId": "https://example.org/Bom-1"},
        {"type": "SpdxDocument", "spdxId": "https://example.org/Doc-1"},
        {"type": "CreationInfo", "@id": "_:CreationInfo0"},
        {"type": "software_Package", "spdxId": "https://example.org/Package-1"},
    ]
    sorted_elements = sorted(elements, key=_graph_sort_key)
    sorted_types = [e["type"] for e in sorted_elements]

    assert sorted_types[0] == "CreationInfo"
    assert sorted_types[1] == "SpdxDocument"
    assert sorted_types[2] == "Bom"
    assert sorted_types[3] == "software_Sbom"
    assert sorted_types[4] == "software_Package"


_CONTENT_TYPE_RE = re.compile(r"^[^/]+/[^/]+$")


def test_spdx3_provenance_annotations_are_compliant() -> None:
    """Every emitted provenance Annotation satisfies the Core/Annotation
    shape: required subject/annotationType, a resolvable subject spdxId, and
    a contentType matching the spec's ``^[^/]+/[^/]+$`` pattern."""
    pyproject_content = """
[project]
name = "test-annotation-compliance"
version = "1.0.0"
description = "Testing Annotation compliance"
dependencies = ["requests>=2.28.0"]
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        pyproject_path = tmppath / "pyproject.toml"
        pyproject_path.write_text(pyproject_content)

        sbom_json = generate_project_sbom(tmppath)
        graph = json.loads(sbom_json)["@graph"]

        all_ids = {e["spdxId"] for e in graph if isinstance(e.get("spdxId"), str)}
        annotations = [e for e in graph if e.get("type") == "Annotation"]
        assert len(annotations) > 0, "expected at least one provenance Annotation"

        for ann in annotations:
            assert ann.get("spdxId")
            assert ann.get("annotationType") == "other"
            assert ann.get("subject") in all_ids
            content_type = ann.get("contentType")
            assert content_type is not None
            assert _CONTENT_TYPE_RE.match(content_type)
            # statement must be valid JSON carrying the pitloom/1 schema marker.
            statement = json.loads(ann["statement"])
            assert statement["schema"] == "https://pitloom.dev/provenance/fields/1"


def test_spdx3_provenance_format_annotation_omits_comment() -> None:
    """With provenance_format='annotation', provenance moves entirely into
    Annotations -- the main package's comment is not set from provenance.
    Uses an ``authors`` entry so a high-signal (inferred copyright) field
    exists under the default minimal detail."""
    pyproject_content = """
[project]
name = "test-annotation-only"
version = "1.0.0"
authors = [{name = "Jane Doe"}]
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        pyproject_path = tmppath / "pyproject.toml"
        pyproject_path.write_text(pyproject_content)

        project_metadata, pitloom_config, _ = read_project(tmppath)
        pitloom_config = dataclasses.replace(
            pitloom_config, provenance_format="annotation"
        )
        sbom_json = generate_project_sbom(
            tmppath,
            project_metadata=project_metadata,
            pitloom_config=pitloom_config,
        )
        graph = json.loads(sbom_json)["@graph"]

        main_package = next(
            e
            for e in graph
            if e.get("type") == "software_Package"
            and e.get("name") == "test-annotation-only"
        )
        assert "comment" not in main_package or main_package["comment"] is None
        annotations = [
            e
            for e in graph
            if e.get("type") == "Annotation"
            and e.get("subject") == main_package["spdxId"]
        ]
        assert len(annotations) == 1
