---
name: Bandit

on:
  push:
    paths: &trigger-paths
      - "src/pitloom/**"
      - "pyproject.toml"
      - ".github/workflows/bandit.yaml"
  pull_request:
    paths: *trigger-paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to the code scanning dashboard
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Bandit
        uses: PyCQA/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f # v1.0.1
        with:
          targets: src/pitloom
